### ISSUE TITLE
Can't change font-size of TabGroup or Tab

### ISSUE THREAD

**Issue by benemuc** [StackOverflowMATLABchat/mlapptools#14]
## Expected Behavior
Thank you for this tool. I really appreciate it.

However, i struggle with the increase of the font size of a tab-group.
I tried the following code:
<pre lang="matlab">
properties (Access = private, Constant = true)
   ID_ATTRIBUTE_NAME = 'id';
end

methods (Access = private)
   % Button pushed function: Button
        function ButtonPushed(app, event)
          IAN = app.ID_ATTRIBUTE_NAME;
           hWin = mlapptools.getWebWindow(app.UIFigure);
          % Return all registered widgets:
          [~,w] = mlapptools.getWidgetList(app.UIFigure);
          % Filter list:
          w = w(~cellfun(@isempty,w.id) & ...
                 cellfun(@(x)~isempty(strfind(x,'uniq')),w.id),:); %#ok<STREMP>
          for ind1 = 1:size(w,1)
              mlapptools.setStyle(hWin,'font-size','200%',struct('ID_attr',IAN,'ID_val',w{ind1,IAN}{1}));
          end
        end
    end
</pre>

This code increased the font size of all elements, but without the tab-group (or tabs) font size.

Isn´t it possible to increase the font size of tab-groups (or tabs)?

Thanks a lot!

## Actual Behavior
![001](https://user-images.githubusercontent.com/35295504/34770848-b341ccb6-f602-11e7-8c1c-d8075a8b9196.jpg)
After pushbutton is clicked, every font-size is encreased, except the tabs:
![002](https://user-images.githubusercontent.com/35295504/34770885-d86cbd3e-f602-11e7-9ab5-e3b132daef0a.png)

## Specifications

  - MATLAB Release: R2017b
  - Operating System: W10

**Comment by Dev-iL** [comment]
If you take a look at #12, you'll get the idea that tabs / tab-groups belong to the more complex element types.

I made a sample `uifigure` to test your problem (please try to provide something like this yourself if you report further issues in the future):

```matlab
f = uifigure();
tg = uitabgroup(f);
t1 = uitab(tg,'Title','Tab1');
t2 = uitab(tg,'Title','Tab2');
[win, widgetID] = mlapptools.getWebElements(tg);
```

Digging through the dumped HTML code, it seems that the tab text is found in the 3<sup>rd</sup> `<span>` child of `widgetid="uniqName_106_0_tablist_uniqName_30_0"`,

    <span class="mwTabLabel" data-dojo-attach-point="labelNode,containerNode">Tab1</span>

I tried changing the size of the text inside this `<span>`, but that proved quite useless since it doesn't increase the tab size accordingly so much of the text becomes cropped.

Therefore, I believe these elements should be modified somehow through Dijit ([possible clue](https://dojotoolkit.org/reference-guide/1.10/dijit/layout/TabContainer.html)), but I have no idea how... :\

My temporary suggestion is overwriting the CSS attributes of all tab headers by writing some new style attributes into `<html><head><script>...` like so:

```matlab
win.executeJS(['document.head.getElementsByTagName("style")[0].innerHTML = ' ...
  '".mwTabContainer .mwTabLabel {font-size: 16px; overflow: visible}"']);
```

So a full example would be:

```matlab
f = uifigure('Position',[338,477,393,246],'Resize','off');
tg = uitabgroup(f); 
t1 = uitab(tg,'Title','SomeLongerStringToMakeRoom');
t2 = uitab(tg,'Title','Tab2---');
[win, widgetID] = mlapptools.getWebElements(tg);

win.executeJS(['document.head.getElementsByTagName("style")[0].innerHTML = ' ...
  '".mwTabContainer .mwTabLabel {font-size: 22px; overflow: visible}"']);

t1.Title = 'ActualString';
t2.Title = 'Tab2';
tg.Position = tg.Position.*[1 1 1.4 1];

childID = mlapptools.getChildNodeIDs(win,widgetID);
mlapptools.setStyle(win,'height','40px',childID(2));
childID = mlapptools.getChildNodeIDs(win,childID(2));
mlapptools.setStyle(win,'height','40px',childID(4));
mlapptools.setStyle(win,'height','40px',childID(5));
```

Which results in:

![untitled](https://user-images.githubusercontent.com/6509619/34777520-4237d36e-f623-11e7-90e6-48a255443d77.png)

**Comment by benemuc** [comment]
Thanks a lot!

**Comment by Dev-iL** [comment]
@benemuc I changed the font not by styling a specific element, but by tapping into the CSS definition of the entire `uifigure` (sort of). If it's still unclear, please join me [in chat](https://chat.stackoverflow.com/rooms/81987/chatlab-and-talktave) - it would be easier to explain that way.
